In [1]:
import os
os.chdir(r"C:\Users\dasab\Downloads")

In [2]:
import pandas as pd
df = pd.read_csv("Banking.csv")
df.head()

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Client ID                 3000 non-null   object
 1   Name                      3000 non-null   object
 2   Age                       3000 non-null   int64
 3   Location ID               3000 non-null   int64
 4   Joined Bank               3000 non-null   object
 5   Banking Contact           3000 non-null   object
 6   Nationality               3000 non-null   object
 7   Occupation                3000 non-null   object
 8   Fee Structure             3000 non-null   object
 9   Loyalty Classification    3000 non-null   object
 10  Estimated Income          3000 non-null   float64
 11  Superannuation Savings    3000 non-null   float64
 12  Amount of Credit Cards    3000 non-null   int64
 13  Credit Card Balance       3000 non-null   float64
 14  Bank Loans                3000 non-null   float64
 15  Bank Deposits             3000 non-null   float64
 16  Checking Accounts         3000 non-null   float64
 17  Saving Accounts           3000 non-null   float64
 18  Foreign Currency Account  3000 non-null   float64
 19  Business Lending          3000 non-null   float64
 20  Properties Owned          3000 non-null   int64
 21  Risk Weighting            3000 non-null   int64
 22  BRId                      3000 non-null   int64
 23  GenderId                  3000 non-null   int64
 24  IAId                      3000 non-null   int64
dtypes: float64(9), int64(8), object(8)
memory usage: 586.1+ KB

In [4]:
df.describe()

,Age,Location ID,Estimated Income,Superannuation Savings,Amount of Credit Cards,Credit Card Balance,Bank Loans,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3.000000e+03,3.000000e+03,3.000000e+03,3000.000000,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,51.039667,21563.323000,171305.034263,25531.599673,1.463667,3176.206943,5.913862e+05,6.715602e+05,3.210929e+05,2.329084e+05,29883.529993,8.667598e+05,1.518667,2.249333,2.559333,1.504000,10.425333
std,19.854760,12462.273017,111935.808209,16259.950770,0.676387,2497.094709,4.575570e+05,6.457169e+05,2.820796e+05,2.300078e+05,23109.924010,6.412303e+05,1.102145,1.131191,1.007713,0.500067,5.988242
min,17.000000,12.000000,15919.480000,1482.030000,1.000000,1.170000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,45.000000,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000
25%,34.000000,10803.500000,82906.595000,12513.775000,1.000000,1236.630000,2.396281e+05,2.044004e+05,1.199475e+05,7.479440e+04,11916.542500,3.748251e+05,1.000000,1.000000,2.000000,1.000000,5.000000
50%,51.000000,21129.500000,142313.480000,22357.355000,1.000000,2560.805000,4.797934e+05,4.633165e+05,2.428157e+05,1.640866e+05,24341.190000,7.113147e+05,2.000000,2.000000,3.000000,2.000000,10.000000
75%,69.000000,32054.500000,242290.305000,35464.740000,2.000000,4522.632500,8.258130e+05,9.427546e+05,4.348749e+05,3.155750e+05,41966.392500,1.185110e+06,2.000000,3.000000,3.000000,2.000000,15.000000
max,85.000000,43369.000000,522330.260000,75963.900000,3.000000,13991.990000,2.667557e+06,3.890598e+06,1.969923e+06,1.724118e+06,124704.870000,3.825962e+06,3.000000,5.000000,4.000000,2.000000,22.000000

In [5]:
df.isnull().sum()

Client ID                   0
Name                        0
Age                         0
Location ID                 0
Joined Bank                 0
Banking Contact             0
Nationality                 0
Occupation                  0
Fee Structure               0
Loyalty Classification      0
Estimated Income            0
Superannuation Savings      0
Amount of Credit Cards      0
Credit Card Balance         0
Bank Loans                  0
Bank Deposits               0
Checking Accounts           0
Saving Accounts             0
Foreign Currency Account    0
Business Lending            0
Properties Owned            0
Risk Weighting              0
BRId                        0
GenderId                    0
IAId                        0
dtype: int64

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['client_id', 'name', 'age', 'location_id', 'joined_bank',
       'banking_contact', 'nationality', 'occupation', 'fee_structure',
       'loyalty_classification', 'estimated_income', 'superannuation_savings',
       'amount_of_credit_cards', 'credit_card_balance', 'bank_loans',
       'bank_deposits', 'checking_accounts', 'saving_accounts',
       'foreign_currency_account', 'business_lending', 'properties_owned',
       'risk_weighting', 'brid', 'genderid', 'iaid'],
      dtype='object')

In [7]:
df["client_id"].duplicated().sum()

np.int64(60)

In [8]:
df = df.drop_duplicates(subset=["client_id"], keep="first")

In [9]:
df["client_id"].duplicated().sum()

np.int64(0)

In [10]:
df['genderid'] = df['genderid'].replace({1: 'male', 2: 'female'})

In [11]:
df.head()

,client_id,name,age,location_id,joined_bank,banking_contact,nationality,occupation,fee_structure,loyalty_classification,...,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,genderid,iaid
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,male,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,male,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,female,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,male,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,female,5

In [12]:
df.rename(columns = {
    'joined_bank' : 'joined_date',
    'genderid' : 'gender'
},inplace=True)

In [13]:
df.head()

,client_id,name,age,location_id,joined_date,banking_contact,nationality,occupation,fee_structure,loyalty_classification,...,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,gender,iaid
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,male,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,male,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,female,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,male,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,female,5

In [14]:
lables = ['Young', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels=lables )

In [15]:
df[['age', 'age_group']].head(10)

   age    age_group
0   24        Young
1   23        Young
2   27        Young
3   40        Adult
4   46        Adult
5   23        Young
6   46        Adult
7   78       Senior
8   67  Middle-aged
9   51        Adult

In [16]:
df = df.drop(['banking_contact', 'iaid', 'brid'], axis = 1)

In [17]:
df = df.drop('location_id', axis = 1)

In [18]:
df.head()

,client_id,name,age,joined_date,nationality,occupation,fee_structure,loyalty_classification,estimated_income,superannuation_savings,...,bank_loans,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,gender,age_group
0,IND81288,Raymond Mills,24,06-05-2019,American,Safety Technician IV,High,Jade,75384.77,17677.95,...,776242.92,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,male,Young
1,IND65833,Julia Spencer,23,10-12-2001,African,Software Consultant,High,Jade,289834.31,17398.92,...,1270615.43,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,male,Young
2,IND47499,Stephen Murray,27,25-01-2010,European,Help Desk Operator,High,Gold,169935.23,42825.90,...,1052715.84,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,female,Young
3,IND72498,Virginia Garza,40,28-03-2019,American,Geologist II,Mid,Silver,356808.11,5473.15,...,121195.06,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,male,Adult
4,IND60181,Melissa Sanders,46,20-07-2012,American,Assistant Professor,Mid,Platinum,130711.68,48077.60,...,1048301.95,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,female,Adult

In [19]:
df['occupation'] = df['occupation'].str.replace(r'\s+(I|II|III|IV)$', '', regex=True)

In [20]:
df['occupation'].unique()

array(['Safety Technician', 'Software Consultant', 'Help Desk Operator',
       'Geologist', 'Assistant Professor', 'Help Desk Technician',
       'Account Coordinator', 'Automation Specialist',
       'Software Test Engineer', 'Administrative Officer',
       'Database Administrator', 'Staff Scientist', 'Programmer',
       'Actuary', 'Staff Accountant', 'Assistant Media Planner',
       'Compensation Analyst', 'Web Designer', 'Media Manager',
       'Accounting Assistant', 'Administrative Assistant',
       'Geological Engineer', 'Junior Executive', 'Biostatistician',
       'Internal Auditor', 'Chemical Engineer', 'Accountant',
       'Registered Nurse', 'Cost Accountant', 'Developer',
       'Software Engineer', 'Nurse', 'Human Resources Manager',
       'Analyst Programmer', 'Senior Editor', 'Health Coach',
       'Web Developer', 'Systems Administrator', 'Project Manager',
       'Engineer', 'Human Resources Assistant', 'Sales Associate',
       'Dental Hygienist', 'Associate Professor',
       'Computer Systems Analyst', 'Electrical Engineer', 'Statistician',
       'Programmer Analyst', 'Technical Writer', 'Recruiter',
       'Senior Developer', 'Office Assistant', 'Operator', 'Editor',
       'Analog Circuit Design manager', 'VP Marketing', 'Civil Engineer',
       'Senior Quality Engineer', 'VP Accounting',
       'Information Systems Manager', 'Speech Pathologist', 'Paralegal',
       'Budget/Accounting Analyst', 'Senior Financial Analyst',
       'Product Engineer', 'Data Coordiator', 'Account Representative',
       'Mechanical Systems Engineer', 'VP Product Management',
       'Business Systems Development Analyst', 'Teacher',
       'Marketing Assistant', 'Structural Engineer', 'Research Associate',
       'Quality Control Specialist', 'Environmental Specialist',
       'Structural Analysis Engineer', 'Pharmacist',
       'Payment Adjustment Coordinator', 'Account Executive',
       'Social Worker', 'Community Outreach Specialist',
       'Financial Advisor', 'Research Nurse', 'Research Assistant',
       'Quality Engineer', 'Tax Accountant', 'Marketing Manager',
       'VP Quality Control', 'Chief Design Engineer', 'VP Sales',
       'Food Chemist', 'Assistant Manager', 'Executive Secretary',
       'Librarian', 'Nuclear Power Engineer', 'Director of Sales',
       'Environmental Tech', 'Graphic Designer', 'Professor',
       'Physical Therapy Assistant', 'Legal Assistant', 'Design Engineer',
       'Financial Analyst', 'Occupational Therapist',
       'Clinical Specialist', 'Desktop Support Technician',
       'Senior Cost Accountant', 'GIS Technical Architect',
       'General Manager', 'Nurse Practicioner', 'Recruiting Manager',
       'Sales Representative', 'Senior Sales Associate'], dtype=object)

In [21]:
df["joined_date"].dtype

dtype('O')

In [22]:
df["joined_date"] = pd.to_datetime(df["joined_date"],format="%d-%m-%Y")

In [23]:
df["joined_date"].dtype

dtype('<M8[ns]')

In [26]:
df["fee_structure"] = pd.qcut(df["estimated_income"],q=3,labels=["Low", "Mid", "High"])

In [27]:
df.head()

,client_id,name,age,joined_date,nationality,occupation,fee_structure,loyalty_classification,estimated_income,superannuation_savings,...,bank_loans,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,gender,age_group
0,IND81288,Raymond Mills,24,2019-05-06,American,Safety Technician,Low,Jade,75384.77,17677.95,...,776242.92,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,male,Young
1,IND65833,Julia Spencer,23,2001-12-10,African,Software Consultant,High,Jade,289834.31,17398.92,...,1270615.43,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,male,Young
2,IND47499,Stephen Murray,27,2010-01-25,European,Help Desk Operator,Mid,Gold,169935.23,42825.90,...,1052715.84,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,female,Young
3,IND72498,Virginia Garza,40,2019-03-28,American,Geologist,High,Silver,356808.11,5473.15,...,121195.06,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,male,Adult
4,IND60181,Melissa Sanders,46,2012-07-20,American,Assistant Professor,Mid,Platinum,130711.68,48077.60,...,1048301.95,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,female,Adult

In [28]:
from sqlalchemy import create_engine

engine = create_engine(f"mysql+pymysql://{'root'}:{'AbinashSQL07'}@{'localhost'}:{'3306'}/{'DAP'}")
table_name = "banking"
df.to_sql(table_name, engine, if_exists="replace", index=False)

2940